apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: my-api # Doit correspondre au label dans ton api-deployment.yaml
  ports:
    - protocol: TCP
      port: 80         # Le port que le service écoute
      targetPort: 3000  # Le port sur lequel ton app Node.js écoute
      nodePort: 30000   # Le port sur lequel tu pourras accéder depuis ton PC